### ISSUE TITLE
Blank screen while configuring the pattern options because of rendering loop

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing.org#105]
@glasssteel reports they get the error *Too many re-renders. React limits the number of renders to prevent an infinite loop.*

This seems to happen with some option groups but more research is needed to exactly replicate this.

**Comment by GlassSteel** [comment]
I have a recipe that will replicate this error every time, if that helps.

**Comment by joostdecock** [comment]
Sure thing, please post the link to it :)

**Comment by GlassSteel** [comment]
[This is the recipe](https://freesewing.org/recipes/mrrij/)

[Replicate it](https://freesewing.org/recreate/mrrij/replica), then click the "Style" heading to attempt to access those options - blank screen every time for me (OSX & Chrome), same React error message.

Let me know if I need to enable permissions in some way so you can view these links.

**Comment by joostdecock** [comment]
Thanks. That does break it indeed.

**Comment by kieranklaassen** [comment]
It seems this is a bug in `@freesewing/components/DraftConfigurator`.

https://app.bugsnag.com/freesewing/freesewing-dot-org/errors/5d726fcc286d060019a2b737?filters[event.since][0]=30d&filters[error.status][0]=open

**Comment by kieranklaassen** [comment]
```
react-dom.development.js:15693 Uncaught Invariant Violation: Too many re-renders. React limits the number of renders to prevent an infinite loop.
    at http://localhost:8000/commons.js:109227:26
    at dispatchAction (http://localhost:8000/commons.js:109230:5)
    at FormFieldList (http://localhost:8000/commons.js:6273:12282)
    at renderWithHooks (http://localhost:8000/commons.js:108661:18)
    at mountIndeterminateComponent (http://localhost:8000/commons.js:110873:13)
    at beginWork$1 (http://localhost:8000/commons.js:112017:16)
    at HTMLUnknownElement.callCallback (http://localhost:8000/commons.js:93882:14)
    at HTMLUnknownElement.__trace__ (http://localhost:8000/commons.js:5034:28)
    at Object.invokeGuardedCallbackDev (http://localhost:8000/commons.js:93932:16)
    at invokeGuardedCallback (http://localhost:8000/commons.js:93989:31)
    at beginWork$$1 (http://localhost:8000/commons.js:116748:7)
    at performUnitOfWork (http://localhost:8000/commons.js:115739:12)
    at workLoopSync (http://localhost:8000/commons.js:115716:22)
    at renderRoot (http://localhost:8000/commons.js:115409:11)
    at runRootCallback (http://localhost:8000/commons.js:115085:20)
    at http://localhost:8000/commons.js:104888:24
    at unstable_runWithPriority (http://localhost:8000/commons.js:119977:12)
    at runWithPriority$2 (http://localhost:8000/commons.js:104840:10)
    at flushSyncCallbackQueueImpl (http://localhost:8000/commons.js:104884:7)
    at flushSyncCallbackQueue (http://localhost:8000/commons.js:104873:3)
    at discreteUpdates$1 (http://localhost:8000/commons.js:115208:7)
    at discreteUpdates (http://localhost:8000/commons.js:95894:12)
    at dispatchDiscreteEvent (http://localhost:8000/commons.js:99514:3)
    at HTMLDocument.__trace__ (http://localhost:8000/commons.js:5034:28)
(anonymous) @ react-dom.development.js:15693
dispatchAction @ react-dom.development.js:15696
FormFieldList @ index.js:6
renderWithHooks @ react-dom.development.js:15127
mountIndeterminateComponent @ react-dom.development.js:17339
beginWork$1 @ react-dom.development.js:18483
callCallback @ react-dom.development.js:348
__trace__ @ bugsnag.js:2230
invokeGuardedCallbackDev @ react-dom.development.js:398
invokeGuardedCallback @ react-dom.development.js:455
beginWork$$1 @ react-dom.development.js:23214
performUnitOfWork @ react-dom.development.js:22205
workLoopSync @ react-dom.development.js:22182
renderRoot @ react-dom.development.js:21875
runRootCallback @ react-dom.development.js:21551
(anonymous) @ react-dom.development.js:11354
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11306
flushSyncCallbackQueueImpl @ react-dom.development.js:11350
flushSyncCallbackQueue @ react-dom.development.js:11339
discreteUpdates$1 @ react-dom.development.js:21674
discreteUpdates @ react-dom.development.js:2360
dispatchDiscreteEvent @ react-dom.development.js:5980
__trace__ @ bugsnag.js:2230
index.js:2177 The above error occurred in the <FormFieldList> component:
    in FormFieldList (created by PatternOptionList)
    in div (created by OptionPreamble)
    in OptionPreamble (created by InjectIntl(OptionPreamble))
    in InjectIntl(OptionPreamble) (created by PatternOptionList)
    in li (created by PatternOptionList)
    in PatternOptionList (created by OptionGroup)
    in OptionGroup (created by InjectIntl(OptionGroup))
    in InjectIntl(OptionGroup) (created by PatternOptions)
    in ul (created by PatternOptions)
    in li (created by PatternOptions)
    in ul (created by PatternOptions)
    in PatternOptions (created by DraftConfigurator)
    in li (created by DraftConfigurator)
    in ul (created by DraftConfigurator)
    in DraftConfigurator (at draft.js:314)
    in div (at draft.js:476)
    in aside (at draft.js:475)
    in div (at draft.js:463)
    in DraftPage (created by d)
    in d (at draft/index.js:32)
    in LoginRequired (at draft/index.js:41)
    in DraftIndex (at main-page.js:57)
    in MainPage (at app/index.js:152)
    in div (at app/index.js:219)
    in ThemeProvider (at app/index.js:206)
    in ErrorBoundary (at app/index.js:205)
    in App (created by InjectIntl(App))
    in InjectIntl(App) (created by _class)
    in IntlProvider (at withLanguage.js:26)
    in _class (created by d)
    in d (created by HotExportedd)
    in AppContainer (created by HotExportedd)
    in HotExportedd (created by PageRenderer)
    in PageRenderer (at json-store.js:93)
    in JSONStore (at root.js:51)
    in RouteHandler (at root.js:73)
    in div (created by FocusHandlerImpl)
    in FocusHandlerImpl (created by Context.Consumer)
    in FocusHandler (created by RouterImpl)
    in RouterImpl (created by Context.Consumer)
    in Location (created by Context.Consumer)
    in Router (created by EnsureResources)
    in ScrollContext (at root.js:64)
    in RouteUpdates (at root.js:63)
    in EnsureResources (at root.js:61)
    in LocationHandler (at root.js:119)
    in LocationProvider (created by Context.Consumer)
    in Location (at root.js:118)
    in Root (at root.js:126)
    in MDXProvider (at wrap-root-element.js:65)
    in MDXScopeProvider (at wrap-root-element.js:64)
    in Unknown
    in Unknown (at wrap-root-element.js:72)
    in _default (at app.js:67)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
__stack_frame_overlay_proxy_console__ @ index.js:2177
r @ backend.js:1
logCapturedError @ react-dom.development.js:19811
logError @ react-dom.development.js:19847
callback @ react-dom.development.js:20958
callCallback @ react-dom.development.js:12930
commitUpdateEffects @ react-dom.development.js:12969
commitUpdateQueue @ react-dom.development.js:12960
commitLifeCycles @ react-dom.development.js:20076
commitLayoutEffects @ react-dom.development.js:22810
callCallback @ react-dom.development.js:348
__trace__ @ bugsnag.js:2230
invokeGuardedCallbackDev @ react-dom.development.js:398
invokeGuardedCallback @ react-dom.development.js:455
commitRootImpl @ react-dom.development.js:22582
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11306
commitRoot @ react-dom.development.js:22411
runRootCallback @ react-dom.development.js:21551
(anonymous) @ react-dom.development.js:11354
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11306
flushSyncCallbackQueueImpl @ react-dom.development.js:11350
flushSyncCallbackQueue @ react-dom.development.js:11339
discreteUpdates$1 @ react-dom.development.js:21674
discreteUpdates @ react-dom.development.js:2360
dispatchDiscreteEvent @ react-dom.development.js:5980
__trace__ @ bugsnag.js:2230
index.js:2177 The above error occurred in the <FormFieldList> component:
    in FormFieldList (created by PatternOptionList)
    in div (created by OptionPreamble)
    in OptionPreamble (created by InjectIntl(OptionPreamble))
    in InjectIntl(OptionPreamble) (created by PatternOptionList)
    in li (created by PatternOptionList)
    in PatternOptionList (created by OptionGroup)
    in ul (created by OptionGroup)
    in OptionGroup (created by InjectIntl(OptionGroup))
    in InjectIntl(OptionGroup) (created by PatternOptions)
    in ul (created by PatternOptions)
    in li (created by PatternOptions)
    in ul (created by PatternOptions)
    in PatternOptions (created by DraftConfigurator)
    in li (created by DraftConfigurator)
    in ul (created by DraftConfigurator)
    in DraftConfigurator (at draft.js:314)
    in div (at draft.js:476)
    in aside (at draft.js:475)
    in div (at draft.js:463)
    in DraftPage (created by d)
    in d (at draft/index.js:32)
    in LoginRequired (at draft/index.js:41)
    in DraftIndex (at main-page.js:57)
    in MainPage (at app/index.js:152)
    in div (at app/index.js:219)
    in ThemeProvider (at app/index.js:206)
    in ErrorBoundary (at app/index.js:205)
    in App (created by InjectIntl(App))
    in InjectIntl(App) (created by _class)
    in IntlProvider (at withLanguage.js:26)
    in _class (created by d)
    in d (created by HotExportedd)
    in AppContainer (created by HotExportedd)
    in HotExportedd (created by PageRenderer)
    in PageRenderer (at json-store.js:93)
    in JSONStore (at root.js:51)
    in RouteHandler (at root.js:73)
    in div (created by FocusHandlerImpl)
    in FocusHandlerImpl (created by Context.Consumer)
    in FocusHandler (created by RouterImpl)
    in RouterImpl (created by Context.Consumer)
    in Location (created by Context.Consumer)
    in Router (created by EnsureResources)
    in ScrollContext (at root.js:64)
    in RouteUpdates (at root.js:63)
    in EnsureResources (at root.js:61)
    in LocationHandler (at root.js:119)
    in LocationProvider (created by Context.Consumer)
    in Location (at root.js:118)
    in Root (at root.js:126)
    in MDXProvider (at wrap-root-element.js:65)
    in MDXScopeProvider (at wrap-root-element.js:64)
    in Unknown
    in Unknown (at wrap-root-element.js:72)
    in _default (at app.js:67)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

**Comment by joostdecock** [comment]
My current working theory is that this is something specific to the *recreate* functionality.
I was unable to reproduce this when creating a pattern, but I did reproduce it when **re**creating one.

**Comment by joostdecock** [comment]
Fixed in https://github.com/freesewing/freesewing/commit/983886df8348c876c03c283f558e7fd39a6197ab
