### ISSUE TITLE
Unhandled exception drafting Florent

### ISSUE THREAD

**Issue by woolishboy** [freesewing/freesewing.org#316]
Drafted new Florent pattern and got the "known bug in svg library" display. Set seam allowance to 0 and it drafted correctly, but then setting paperless to "yes" caused the following exception:
```
TypeError: Cannot read property 'type' of undefined
    at b.AxEy.b.edge (https://freesewing.org/component---src-components-app-index-js-d0568c8ee03c1f3177cb.js:1:1587891)
    at n.ud.draftBrimTop (https://freesewing.org/component---src-components-app-index-js-d0568c8ee03c1f3177cb.js:1:1158766)
    at n.AxEy.U.draft (https://freesewing.org/component---src-components-app-index-js-d0568c8ee03c1f3177cb.js:1:1609623)
    at https://freesewing.org/component---src-components-app-index-js-d0568c8ee03c1f3177cb.js:1:1472239
    at Ai (https://freesewing.org/commons-806211d12bb5e4bfad82.js:1:67998)
    at va (https://freesewing.org/commons-806211d12bb5e4bfad82.js:1:75039)
    at Zo (https://freesewing.org/commons-806211d12bb5e4bfad82.js:1:112187)
    at Bo (https://freesewing.org/commons-806211d12bb5e4bfad82.js:1:96555)
    at Wo (https://freesewing.org/commons-806211d12bb5e4bfad82.js:1:93582)
    at Oo (https://freesewing.org/commons-806211d12bb5e4bfad82.js:1:92155)
```
I was able to reproduce.

**Comment by joostdecock** [comment]
I'm fairly confident that this is fixed in the upcoming 2.2 release (I can no longer reproduce it). 
I'm closing this. If you bump into it again, please create an issue for it, or comment here to re-open.
