### ISSUE TITLE
Stack trace

### ISSUE THREAD

**Issue by dimurano** [freesewing/freesewing.org#369]
Stack trace
TypeError: Cannot read property 'x' of undefined
    at c.AxEy.c.sitsOn (https://freesewing.org/component---src-components-app-index-js-7871a174e10fa41da208.js:1:1566727)
    at T (https://freesewing.org/component---src-components-app-index-js-7871a174e10fa41da208.js:1:1592454)
    at b.AxEy.b.split (https://freesewing.org/component---src-components-app-index-js-7871a174e10fa41da208.js:1:1604005)
    at https://freesewing.org/component---src-components-app-index-js-7871a174e10fa41da208.js:1:1061012
    at n.Sp.draftFront (https://freesewing.org/component---src-components-app-index-js-7871a174e10fa41da208.js:1:1062434)
    at n.AxEy.U.draft (https://freesewing.org/component---src-components-app-index-js-7871a174e10fa41da208.js:1:1622714)
    at https://freesewing.org/component---src-components-app-index-js-7871a174e10fa41da208.js:1:1480087
    at pi (https://freesewing.org/commons-cf4f0adf3f8220da469d.js:1:71204)
    at Xi (https://freesewing.org/commons-cf4f0adf3f8220da469d.js:1:79404)
    at zo (https://freesewing.org/commons-cf4f0adf3f8220da469d.js:1:117614)

**Comment by joostdecock** [comment]
Thanks for reporting this. Could you share your username as well as the pattern & model you were using?

That will allow us to reproduce this.

**Comment by joostdecock** [comment]
Closing due to lack of feedback
