### ISSUE TITLE
Simone shirt error

### ISSUE THREAD

**Issue by GitBen2** [freesewing/freesewing.org#537]
Simon shirt produces the following error message:

TypeError: n[k].rotate is not a function
    at o.ne.draftFbaFront (https://freesewing.org/component---src-pages-create-design-for-person-js-017e8aa9e9adddbd9dbc.js:1:1361291)
    at o.AxEy.U.draft (https://freesewing.org/component---src-pages-create-design-for-person-js-017e8aa9e9adddbd9dbc.js:1:233065)
    at e.a (https://freesewing.org/component---src-pages-create-design-for-person-js-017e8aa9e9adddbd9dbc.js:1:1476309)
    at ci (https://freesewing.org/commons-c91e1a494c67f3c2b90e.js:1:675992)
    at Yi (https://freesewing.org/commons-c91e1a494c67f3c2b90e.js:1:684214)
    at Ts (https://freesewing.org/commons-c91e1a494c67f3c2b90e.js:1:722253)
    at hl (https://freesewing.org/commons-c91e1a494c67f3c2b90e.js:1:706678)
    at fl (https://freesewing.org/commons-c91e1a494c67f3c2b90e.js:1:706603)
    at al (https://freesewing.org/commons-c91e1a494c67f3c2b90e.js:1:703951)
    at https://freesewing.org/commons-c91e1a494c67f3c2b90e.js:1:662393

**Comment by joostdecock** [comment]
Thank you for reporting this. Could you share your username on the site as well as the person you're creating Simone for, so we can reproduce this?

**Comment by joostdecock** [comment]
Stale, and lacking info. Closing.
