### ISSUE TITLE
Error: points is not defined when changing the number of panels on Cathrin corset

### ISSUE THREAD

**Issue by fevers** [freesewing/freesewing.org#619]
Cathrin corset defaults to 13 panels; when I select 11, pattern throws an error. I have to reset the number of panels to make the error stop showing up.
Stack trace
ReferenceError: points is not defined
    at o.tt.draftPanel1 (https://freesewing.org/component---src-pages-create-design-for-person-js-543398fff5814c90854e.js:1:140460)
    at o.AxEy.U.draft (https://freesewing.org/component---src-pages-create-design-for-person-js-543398fff5814c90854e.js:1:663099)
    at e.a (https://freesewing.org/component---src-pages-create-design-for-person-js-543398fff5814c90854e.js:1:1453921)
    at Ka (https://freesewing.org/commons-305dfb2461615146b64b.js:1:687036)
    at Ii (https://freesewing.org/commons-305dfb2461615146b64b.js:1:695897)
    at gs (https://freesewing.org/commons-305dfb2461615146b64b.js:1:734445)
    at ul (https://freesewing.org/commons-305dfb2461615146b64b.js:1:725770)
    at sl (https://freesewing.org/commons-305dfb2461615146b64b.js:1:725695)
    at Xs (https://freesewing.org/commons-305dfb2461615146b64b.js:1:722776)
    at https://freesewing.org/commons-305dfb2461615146b64b.js:1:674438

**Comment by joostdecock** [comment]
Thank you for reporting this. I'll look in to it.

**Comment by joostdecock** [comment]
Thank you for your patience. This has been fixed in the develop branch. This fix will be available in our next release.
