### ISSUE TITLE
Error Breanna Body block

### ISSUE THREAD

**Issue by besuem** [freesewing/freesewing.org#626]
An error message keeps showing when I try to generate a custom breanna body block with my measurements.

**Comment by joostdecock** [comment]
Could you paste the complete error message here? Or share your username/model so we can reproduce this?

tx

**Comment by besuem** [comment]
Oh sorry!
Here it is: 

Oh no!
There was an unexpected problem. Please report this.

TypeError: r.scyeDart1.shiftTowards is not a function


Stack trace
TypeError: r.scyeDart1.shiftTowards is not a function
    at o.T.draftFrontBase (https://freesewing.org/component---src-pages-create-design-for-person-js-543398fff5814c90854e.js:1:34557)
    at o.AxEy.U.draft (https://freesewing.org/component---src-pages-create-design-for-person-js-543398fff5814c90854e.js:1:663099)
    at e.a (https://freesewing.org/component---src-pages-create-design-for-person-js-543398fff5814c90854e.js:1:1453921)
    at Ka (https://freesewing.org/commons-305dfb2461615146b64b.js:1:687036)
    at Ii (https://freesewing.org/commons-305dfb2461615146b64b.js:1:695897)
    at gs (https://freesewing.org/commons-305dfb2461615146b64b.js:1:734445)
    at ul (https://freesewing.org/commons-305dfb2461615146b64b.js:1:725770)
    at sl (https://freesewing.org/commons-305dfb2461615146b64b.js:1:725695)
    at Xs (https://freesewing.org/commons-305dfb2461615146b64b.js:1:722776)
    at https://freesewing.org/commons-305dfb2461615146b64b.js:1:674438

**Comment by joostdecock** [comment]
Ok, I'll have to look into that. Can you share your username on the site so I can reproduce this?

**Comment by besuem** [comment]
My username is Besuem. I was trying to use the measurements for "Beth".

**Comment by joostdecock** [comment]
Super, thanks. I'll try to look into it tonight.

**Comment by besuem** [comment]
Thank you so much!

**Comment by joostdecock** [comment]
Could you double-check your shoulder to shoulder measurement?
I don't want to go into details here, as this is a public forum, but it seems unlikely to be correct given the rest of your measurements.

I'm not saying it's wrong, I'm just asking to double-check :)

**Comment by besuem** [comment]
So I double checked and my shoulder to shoulder measurement was off by a couple cm. I input the correct measurement but the error message is still coming up.

**Comment by besuem** [comment]
OK nevermind. I had another friend re-measure all my measurements. After inputing all the new measurements, it now works. 
Sorry to waste you time.

**Comment by joostdecock** [comment]
Ok, glad to hear it worked out for you :)
I'll close this now, but if you run into any problems, don't hesitate to create another issue.
