### ISSUE TITLE
error with Wahid

### ISSUE THREAD

**Issue by throwawayfazan** [freesewing/freesewing.org#672]
Error appeared when trying to set hem curve to 0

Error: Error in Path.shiftAlong(): Ran out of path to shift along. Distance requested was 2, path length is0.

Stack trace
Error: Error in Path.shiftAlong(): Ran out of path to shift along. Distance requested was 2, path length is0.
    at x.AxEy.x.shiftAlong (https://en.freesewing.org/component---src-pages-create-design-for-person-js-456d19e2ed9d8de09be1.js:1:633163)
    at https://en.freesewing.org/component---src-pages-create-design-for-person-js-456d19e2ed9d8de09be1.js:1:630564
    at x.AxEy.x.offset (https://en.freesewing.org/component---src-pages-create-design-for-person-js-456d19e2ed9d8de09be1.js:1:630911)
    at https://en.freesewing.org/component---src-pages-create-design-for-person-js-456d19e2ed9d8de09be1.js:1:418049
    at o.Ie.draftFront (https://en.freesewing.org/component---src-pages-create-design-for-person-js-456d19e2ed9d8de09be1.js:1:420464)
    at o.AxEy.J.draft (https://en.freesewing.org/component---src-pages-create-design-for-person-js-456d19e2ed9d8de09be1.js:1:655441)
    at e.a (https://en.freesewing.org/component---src-pages-create-design-for-person-js-456d19e2ed9d8de09be1.js:1:1069452)
    at Ki (https://en.freesewing.org/framework-5a7bf077542a910ca662.js:1:70048)
    at Fa (https://en.freesewing.org/framework-5a7bf077542a910ca662.js:1:78909)
    at vo (https://en.freesewing.org/framework-5a7bf077542a910ca662.js:1:117457)

**Comment by joostdecock** [comment]
Thanks for reporting this.  
I've prevented the hem radius option from being zero, and added the `square` hem style instead for those who want that look.

These changes will be part of the upcoming 2.7.1 release.
