### ISSUE TITLE
Simone Shirt 

### ISSUE THREAD

**Issue by stesews** [freesewing/freesewing.org#714]
Unexpected error appearing when i try and make pattern with wife's measurements

TypeError: n[w].rotate is not a function
    at o.Be.draftFbaFront (https://freesewing.org/component---src-pages-create-design-for-person-js-8d27888b7fdaab612c95.js:1:358434)
    at o.AxEy.J.draft (https://freesewing.org/component---src-pages-create-design-for-person-js-8d27888b7fdaab612c95.js:1:656202)
    at e.a (https://freesewing.org/component---src-pages-create-design-for-person-js-8d27888b7fdaab612c95.js:1:1073231)
    at Ki (https://freesewing.org/framework-5a7bf077542a910ca662.js:1:70048)
    at Fa (https://freesewing.org/framework-5a7bf077542a910ca662.js:1:78909)
    at vo (https://freesewing.org/framework-5a7bf077542a910ca662.js:1:117457)
    at cu (https://freesewing.org/framework-5a7bf077542a910ca662.js:1:108782)
    at ou (https://freesewing.org/framework-5a7bf077542a910ca662.js:1:108707)
    at Zo (https://freesewing.org/framework-5a7bf077542a910ca662.js:1:105788)
    at https://freesewing.org/framework-5a7bf077542a910ca662.js:1:57450

**Comment by joostdecock** [comment]
Can you share your username on the site, so I can try to reproduce this?

tx

**Comment by stesews** [comment]
Hi

I'm logged in as Stephen2 and the person I was trying to create it for was Mags.

Thanks

Ste

**Comment by joostdecock** [comment]
I think you'll need to get out your measuring tape and double-check some of Mags' measurements.

There's a bunch of them that cannot possibly be correct. Such as the bust span being higher than the front bust measurement (which includes the bust span).

Check the documentation for the measurements required for breanna here: https://freesewing.org/docs/patterns/breanna/measurements/
And if you questions, feel free to stop by our chat room: https://gitter.im/freesewing/help
