### ISSUE TITLE
Error Drafting Jarger front as a single part

### ISSUE THREAD

**Issue by enyachoke** [freesewing/freesewing.org#718]
I want creat a muslin for Jarger to to try out the fit. Since am using a plotter I want to draft download the larger pieces separately  I get this issue when I select only front piece. Am drafting this for Men size S
```
Stack trace
TypeError: t.points[o].clone is not a function
    at Y.AxEy.Y.inject (https://freesewing.org/component---src-pages-create-design-for-person-js-8d27888b7fdaab612c95.js:1:644610)
    at o.AxEy.J.draft (https://freesewing.org/component---src-pages-create-design-for-person-js-8d27888b7fdaab612c95.js:1:656004)
    at e.a (https://freesewing.org/component---src-pages-create-design-for-person-js-8d27888b7fdaab612c95.js:1:1073231)
    at Ki (https://freesewing.org/framework-5a7bf077542a910ca662.js:1:70048)
    at Fa (https://freesewing.org/framework-5a7bf077542a910ca662.js:1:78909)
    at vo (https://freesewing.org/framework-5a7bf077542a910ca662.js:1:117457)
    at cu (https://freesewing.org/framework-5a7bf077542a910ca662.js:1:108782)
    at ou (https://freesewing.org/framework-5a7bf077542a910ca662.js:1:108707)
    at Zo (https://freesewing.org/framework-5a7bf077542a910ca662.js:1:105788)
    at https://freesewing.org/framework-5a7bf077542a910ca662.js:1:57450
```

**Comment by joostdecock** [comment]
Thanks for reporting this. I've fixed it. The fix will be part of the upcoming 2.7 release.
