### ISSUE TITLE
Whoops!  Selecting both a separate button placket and separate buttonhole placket blew my Simone pattern up.

### ISSUE THREAD

**Issue by DocSpencer77** [freesewing/freesewing.org#833]
copy and past of the resulting stack trace:
TypeError: Cannot read property 'anchor' of undefined
    at i.ZMXy.x.draftButtonholePlacket (https://freesewing.org/4d90dbe830f6af6b1b9b218343a74e4baa7daf3e-43bd69f90b61fc2c958a.js:1:832441)
    at o.Pe.Be. [as draftButtonholePlacket] (https://freesewing.org/4d90dbe830f6af6b1b9b218343a74e4baa7daf3e-43bd69f90b61fc2c958a.js:1:353320)
    at o.AxEy.J.draft (https://freesewing.org/4d90dbe830f6af6b1b9b218343a74e4baa7daf3e-43bd69f90b61fc2c958a.js:1:599235)
    at t.a (https://freesewing.org/a550341fd3272bdc56bf5664c5e7ad30c4db79b0-ceac1b2268d30bbfeaff.js:1:48884)
    at Ki (https://freesewing.org/framework-aa5d88264b3232f630b4.js:1:70018)
    at Fa (https://freesewing.org/framework-aa5d88264b3232f630b4.js:1:78879)
    at vo (https://freesewing.org/framework-aa5d88264b3232f630b4.js:1:117476)
    at cu (https://freesewing.org/framework-aa5d88264b3232f630b4.js:1:108805)
    at ou (https://freesewing.org/framework-aa5d88264b3232f630b4.js:1:108730)
    at Zo (https://freesewing.org/framework-aa5d88264b3232f630b4.js:1:105760)

A screen snip:
![image](https://user-images.githubusercontent.com/43393580/87888533-11238d80-c9f3-11ea-8e53-55bb30d63f39.png)

I was able to make it blow up twice, even.  :>

Cheers,
Gay

**Comment by joostdecock** [comment]
Fixed in the upcoming 2.7.1 release
